package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"rss/internal/database"
	"time"

	"github.com/google/uuid"
)

// Post Create user hanlder
func (cfg *apiConfig) handlerUsersCreate(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Name string `json = "name"`
	}
	//parsing
	decoder := json.NewDecoder(r.Body)

	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Error parsing JSON: %s", err))
		return
	}
	// if no err, now we hace access to databe to create user
	// the CreateUser method is generated by sqlc and you find it users.sql.go
	user, err := cfg.DB.CreateUser(r.Context(), database.CreateUserParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Name:      params.Name,
	})
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Error creatin user: %s", err))
		return
	}

	respondWithJSON(w, 201, databaseUserToUser(user))
}

// Get user
func (cfg *apiConfig) GetUser(w http.ResponseWriter, r *http.Request, user database.User) {
	respondWithJSON(w, 201, databaseUserToUser(user))
}

// Get posts

func (cfg *apiConfig) GetPosts(w http.ResponseWriter, r *http.Request, user database.User) {
	posts, err := cfg.DB.GetPost(r.Context(), database.GetPostParams{
		UserID: user.ID,
		Limit:  10,
	})
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Error getting posts: %s", err))
		return
	}
	respondWithJSON(w, 201, databasePostsToPosts(posts))
}
